### ISSUE TITLE
Red Dead Redemption 2 Won't Start with wine-wayland

### ISSUE THREAD

**Issue by rothn** [GloriousEggroll/proton-ge-custom#192]
# Compatibility Report
- Name of the game with compatibility issues: Red Dead Redemption 2
- Steam AppID of the game: 1174180

## System Information
- GPU: RX 6900 XT
- Driver/LLVM version: Arch Linux 6.15.9 (builtin driver) ; Mesa 25.1.7
- Kernel version: 6.15.9
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/rothn/582ac63671911acf416f3206d6b8f859
- Proton version: GE-Proton10-10

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-1174180.log](https://github.com/user-attachments/files/21586963/steam-1174180.log)

## Symptoms 
1. Some time after launch, the "Connecting to Rockstar Games" window disappears and a new window appears stating: "An error occurred while authenticating with Rockstar Games services." I am given the option to use Offline Mode, which I click. Note that this does not happen on Steam Proton.
2. After clicking the Offline Mode button, the launcher comes back after some waiting with "Connecting to Rockstar Games"
3. The game hangs and never starts (tested for 15 minutes).

## Reproduction

Note: CLI options required to reproduce: `PROTON_ENABLE_WAYLAND=1 PROTON_ENABLE_HDR=1 ENABLE_HDR_WSI=1 PROTON_LOG=1 %command%`

1. Right click on Red Dead Redemption 2, open Settings, check the box to force use of a specific Steam Play compatibility tool, and select "GE-Proton10-10" 
2. Attempt to launch the game
3. Observe the hang

**Comment by rothn** [comment]
Command-line options (for both): PROTON_ENABLE_WAYLAND=1 PROTON_ENABLE_HDR=1 ENABLE_HDR_WSI=1 PROTON_LOG=1 %command%

**Comment by StephC99** [comment]
Same issue encountered. PROTON_ENABLE_WAYLAND=1 is the main reason why the rockstar launcher won't connect with the personal rockstar account.  Update: I tried PROTON_ENABLE_WAYLAND=1 on proton 10.0-2 (beta) and the game works however its working as XWAYLAND not WAYLAND NATIVE, testing with xorg-xeyes and indeed its xwayland so I don't think proton 10.0-2 (beta) has native wayland support. Tried it again with proton-cachyos-10.0-2 which is known to have native wayland support and just like in Proton GE 10-10 the rockstar game launcher has the login issue.

**Comment by GloriousEggroll** [comment]
upstream proton does not have wine-wayland support enabled nor any of the code surrounding it, therefore PROTON_ENABLE_WAYLAND=1 does nothing on normal proton.

**Comment by rothn** [comment]
> upstream proton does not have wine-wayland support enabled nor any of the code surrounding it, therefore PROTON_ENABLE_WAYLAND=1 does nothing on normal proton.

Understood, and from the logs, it may be a Wine issue relating to undefined behavior with multiple open rendering contexts in Wayland, but I am fairly uncertain about that, and it seems pretty far removed from the main issue of networking not working.

**Comment by nitram3** [comment]
RDR2 has native Vulkan support. Isn't native Vulkan currently not supported on wine Wayland? Unless of course I'm mistaken and you're using DX12 in game.

**Comment by StephC99** [comment]
> RDR2 has native Vulkan support. Isn't native Vulkan currently not supported on wine Wayland? Unless of course I'm mistaken and you're using DX12 in game.

The problem is not in-game, the game starts fine with wayland, but the problem is connecting to the rockstar game launcher since internet connection is required to play even story mode. Something prevents the connection, maybe a missing dependency or incompatibility with the launcher (maybe it prevents connection due to thinking something wayland is doing is suspicious, havent checked a log and the window that pops up on startup is blank).

**Comment by GloriousEggroll** [comment]
> RDR2 has native Vulkan support. Isn't native Vulkan currently not supported on wine Wayland? Unless of course I'm mistaken and you're using DX12 in game.

native vulkan works fine in wine-wayland. the problem isn't related to vulkan but rather wine-wayland cross-process support. there currently isnt a fix.

**Comment by StephC99** [comment]
> > RDR2 has native Vulkan support. Isn't native Vulkan currently not supported on wine Wayland? Unless of course I'm mistaken and you're using DX12 in game.
> 
> native vulkan works fine in wine-wayland. the problem isn't related to vulkan but rather wine-wayland cross-process support. there currently isnt a fix.

Is this something that the wineHQ team can only address?

**Comment by ghost** [comment]
@francislen99 @rothn can you try GE-Proton10-3?

**Comment by StephC99** [comment]
> [@francislen99](https://github.com/francislen99) [@rothn](https://github.com/rothn) can you try GE-Proton10-3?

Just tried it and no doesn't work.

**Comment by GloriousEggroll** [comment]
fixed in 10-14. launcher still renders black but game launches now.

**Comment by StephC99** [comment]
Weird but the issue is still the same for me on proton ge 10-15. Did delete the prefix and run it again.

**Comment by rothn** [comment]
I'm trying on 10-15, and it starts but complains that I'm not signed in and forces me to quit to desktop. I don't think this works yet, @GloriousEggroll

**Comment by abdullahsabbir** [comment]
On 10-14, it is working great, even though the Rockstar launcher UI just renders black, but the game works fine. On 10-15, it's the same as described in the original issue; the launcher doesn't connect to the internet.

**Comment by LemonHeadOnGit** [comment]
Can confirm, Proton GE 10-14 works fine for RDR, GTA etc. but 10-15 or anything lower (tested until 10-10) doesn't work / results in a "connection issue" and the game fails to start.

**Comment by its-turbo** [comment]
This is an open issue for me also.

Manifests a little differently with the launcher half opening and just creates a white box.

https://bbs.archlinux.org/viewtopic.php?id=312037

Person here having the same issue.

**Comment by pvlvld** [comment]
Latest proton / proton-ge / cachyos proton - the same.
Experimental works, tho! yay!

**Comment by loathingKernel** [comment]
> Latest proton / proton-ge / cachyos proton - the same.
> Experimental works, tho! yay!

Experimental doesn't not have `winewayland.drv`, that is why it works. Your env variable is simply ignored.

Guess what happens with either of them when you don't try to use winewayland...

**Comment by pvlvld** [comment]
> > Latest proton / proton-ge / cachyos proton - the same.
> > Experimental works, tho! yay!
> 
> Experimental doesn't not have `winewayland.drv`, that is why it works. Your env variable is simply ignored.

It didn't worked for me neither with or w/o env 🤷
Cachy, Hyprland
