### ISSUE TITLE
Wine-wayland driver causes the game screen to not fit the screen size.

### ISSUE THREAD

**Issue by Linux-Fan** [GloriousEggroll/proton-ge-custom#255]
Does anyone know why the [i]wine-wayland[/i] driver causes the game screen to not fit the screen size, even though everything else works fine?

https://ibb.co/kVz2zcJ7

The game runs on Proton-GE under Heroic Games Launcher.

Here are the details of Wine and screen settings.

https://ibb.co/q34gmgjb

https://ibb.co/WpKvPTTt

**Comment by TerohsLab** [comment]
You can try a few things : 

* Make sure Civ is running in borderless fullscreen or fullscreen
* Since this looks like KDE : Rightclick the civ icon on your bar -> more -> fullscreen
* Force wayland to open the game on the correct screen. `WAYLANDDRV_PRIMARY_MONITOR=DP-1` where DP-1 is the monitor you wanna use. You can find it via `wayland-info`

**Comment by Linux-Fan** [comment]
None ot this seems to work - I guess the driver "thinks" it is working in fullscreen mode, because when I make a change in-game from fullscreen to borderless fullscreen, I get a window with a game that can be moved over my desktop. The window cannot be upscaled to match the full screen size.

https://i.ibb.co/dJV7CRPW/Zrzut-ekranu-20250831-090835.png
https://i.ibb.co/kg76mtqP/Zrzut-ekranu-20250831-090913.png

**Comment by TerohsLab** [comment]
So you are using upscaling? Thats a very crucial part not to mention.

**Comment by Linux-Fan** [comment]
Perhaps I didn't express myself clearly - I do not use any upscaling technique, I just meant that the game window does not match my laptops fullscreen, although it seems it "thinks" it does.

**Comment by vrecek** [comment]
Not sure if this is the same issue, but i have a similar one. I have a 16:9 monitor, and when I use wayland driver (PROTON_ENABLE_WAYLAND=1), and I set in-game resolution different than my aspect ratio resolution(s), it doesnt fit the screen, just like in your case.

**Comment by Linux-Fan** [comment]
I have set ingame resolution exact the same as my Wayland desktop (KDE) and native for the display - 2560x1600.

**Comment by BananaWorks07** [comment]
DPI scaling option in winecfg is broken on winewayland. Use 96 DPI

**Comment by Linux-Fan** [comment]
That seem to do the trick, thank you so much! Is this a known issue to Wine developers?

**Comment by BananaWorks07** [comment]
> That seem to do the trick, thank you so much! Is this a known issue to Wine developers?

It's a bit complicated to explain, but it's probably not going to be an issue there. You can enable DPI scaling for hopefully next proton-ge and everything will work tho

**Comment by Linux-Fan** [comment]
So there will be an environment variable for this in the next release?

**Comment by BananaWorks07** [comment]
> So there will be an environment variable for this in the next release?

No, the bug is fixed

**Comment by GloriousEggroll** [comment]
I plan on putting out a new release with EM-10 fixes this weekend

**Comment by GloriousEggroll** [comment]
marking resolved with 10-18

**Comment by zaps166** [comment]
It still happens in 10-18 and 10-20, steps to reproduce:
- KWin 6.4.5
- 3840x2160 monitor
- run game in full screen mode (e.g. Witcher 3) and change 3840x2160 to 3200x1800
- window doesn't fit entire screen and direct scanout doesn't work anymore

Also setting non 16:9 (different than screen aspect ratio) e.g. 3840x1600 - it fits game on the top instead of the center of the screen (in this case window fits the entire screen).

**Comment by BananaWorks07** [comment]
I misred this issue, i thought it was about DPI scaling. But yes this is still broken since we don't have support for fshack yet.

**Comment by ahmouse15** [comment]
Are there any updates on this? Still experiencing this issue on Rocket League (Steam) with the Wayland driver, on Proton-GE 11-6. Game resolution is set to my display resolution, but the game is larger than the monitor, causing clipping. It is also blurry, as if it's overscaled.

**Comment by BananaWorks07** [comment]
> Are there any updates on this? Still experiencing this issue on Rocket League (Steam) with the Wayland driver, on Proton-GE 11-6. Game resolution is set to my display resolution, but the game is larger than the monitor, causing clipping. It is also blurry, as if it's overscaled.

Do you use gnome? In that case you would need to wait until gnome 51 releases there is a compositor bug in gnome unfortunately

**Comment by ahmouse15** [comment]
> > Are there any updates on this? Still experiencing this issue on Rocket League (Steam) with the Wayland driver, on Proton-GE 11-6. Game resolution is set to my display resolution, but the game is larger than the monitor, causing clipping. It is also blurry, as if it's overscaled.
> 
> Do you use gnome? In that case you would need to wait until gnome 51 releases there is a compositor bug in gnome unfortunately

I'm actually on KDE. On top of blurriness, my mouse position is offset from the cursor, and the game thinks my monitor is 60Hz when it normally realizes it's 165Hz.

Full log (on pastebin since github upload wasn't working): https://pastebin.com/dTDvdmh9

System specs:
```
Launcher: Steam
Proton version: Tested on GE-Proton 11-6 and 
Launch flags: PROTON_ENABLE_WAYLAND=1
Distro: Gentoo
Kernel: 7.1.7
KDE version: 6.6.6
Display server: Wayland
Fractional scaling: 125%

GPU: AMD 7900 XTX
CPU: AMD 7900X
RAM: 64GB
```

**Comment by GloriousEggroll** [comment]
can you please try this test build, there have been a lot of changes added regarding scaling + fractional scaling added after 11-6 released:
https://devbuilds.nobaraproject.org/geproton14/GE-Proton11-6-x86_64.tar.gz

also, please dont make posts with "are there any updates" comments -- the issue is already on the tracker, and if it's open, we know about it. we will get to them when we can. we do this for free in our spare time. dont be pushy or expect any ETA.

**Comment by ahmouse15** [comment]
> can you please try this test build, there have been a lot of changes added regarding scaling + fractional scaling added after 11-6 released: https://devbuilds.nobaraproject.org/geproton14/GE-Proton11-6-x86_64.tar.gz
> 
> also, please dont make posts with "are there any updates" comments -- the issue is already on the tracker, and if it's open, we know about it. we will get to them when we can. we do this for free in our spare time. dont be pushy or expect any ETA.

Thanks. I tried the test build, no visible changes.

Some games have this issue, others don't it seems. Dead by Daylight works fine, but Rocket League has this issue. Maybe to do with DX11 vs DX12?

Another potentially interesting thing is that the actual mouse is up and to the left of where the cursor icon is, but in the steam overlay it's inverted: actual mouse location is down and to the right of the cursor icon.

Also, didn't mean for my original comment to come off that way. Just thought it might've been fixed already but not reflected here, since the last activity was a while ago, and wanted reassurance that the issue wasn't between my keyboard and chair. Truly appreciate the work you and all the contributors are doing, makes gaming on Linux a million times more usable!

**Comment by BananaWorks07** [comment]
> > can you please try this test build, there have been a lot of changes added regarding scaling + fractional scaling added after 11-6 released: https://devbuilds.nobaraproject.org/geproton14/GE-Proton11-6-x86_64.tar.gz
> > also, please dont make posts with "are there any updates" comments -- the issue is already on the tracker, and if it's open, we know about it. we will get to them when we can. we do this for free in our spare time. dont be pushy or expect any ETA.
> 
> Thanks. I tried the test build, no visible changes.
> 
> Some games have this issue, others don't it seems. Dead by Daylight works fine, but Rocket League has this issue. Maybe to do with DX11 vs DX12?
> 
> Another potentially interesting thing is that the actual mouse is up and to the left of where the cursor icon is, but in the steam overlay it's inverted: actual mouse location is down and to the right of the cursor icon.
> 
> Also, didn't mean for my original comment to come off that way. Just thought it might've been fixed already but not reflected here, since the last activity was a while ago, and wanted reassurance that the issue wasn't between my keyboard and chair. Truly appreciate the work you and all the contributors are doing, makes gaming on Linux a million times more usable!

Just to narrow down where the problem could be, could you try with proton-em: https://github.com/BananaWorks07/Proton/actions/runs/33997993691

**Comment by BananaWorks07** [comment]
> > > can you please try this test build, there have been a lot of changes added regarding scaling + fractional scaling added after 11-6 released: https://devbuilds.nobaraproject.org/geproton14/GE-Proton11-6-x86_64.tar.gz
> > > also, please dont make posts with "are there any updates" comments -- the issue is already on the tracker, and if it's open, we know about it. we will get to them when we can. we do this for free in our spare time. dont be pushy or expect any ETA.
> > 
> > 
> > Thanks. I tried the test build, no visible changes.
> > Some games have this issue, others don't it seems. Dead by Daylight works fine, but Rocket League has this issue. Maybe to do with DX11 vs DX12?
> > Another potentially interesting thing is that the actual mouse is up and to the left of where the cursor icon is, but in the steam overlay it's inverted: actual mouse location is down and to the right of the cursor icon.
> > Also, didn't mean for my original comment to come off that way. Just thought it might've been fixed already but not reflected here, since the last activity was a while ago, and wanted reassurance that the issue wasn't between my keyboard and chair. Truly appreciate the work you and all the contributors are doing, makes gaming on Linux a million times more usable!
> 

Just to narrow down where the problem could be, could you try with proton-em: https://github.com/BananaWorks07/Proton/actions/runs/33997993691

> Some games have this issue, others don't it seems. Dead by Daylight works fine, but Rocket League has this issue. Maybe to do with DX11 vs DX12?

If you set a DPI in winecfg, rocket league is not even system DPI aware so that makes this an app bug

> also, please dont make posts with "are there any updates" comments -- the issue is already on the tracker, and if it's open, we know about it. we will get to them when we can. we do this for free in our spare time. dont be pushy or expect any ETA.

This issue should have been closed a while ago, we support D3D exclusive fullscreen and all...

**Comment by ahmouse15** [comment]
> If you set a DPI in winecfg, rocket league is not even system DPI aware so that makes this an app bug

Well, resetting my Wine DPI back to 96 fixed it. Just deleting the prefix also did the trick. I should probably do that next time I have any issues.

It seems I had my Wine DPI set to 120 for Rocket League, to try to workaround this bug when it did exist. I never changed it back, so it seemingly kept the issues even after the fixes were pushed a long time ago (probably in GE 10-18).

It was indeed user error. Thank you for the help.
