### ISSUE TITLE
Stellar Blade UE4SS crashes or does not load after 10-12

### ISSUE THREAD

**Issue by chungyinleo** [GloriousEggroll/proton-ge-custom#269]
# Compatibility Report
- Name of the game with compatibility issues: Stellar Blade
- Steam AppID of the game: 3489700

## System Information
- GPU:  RTX 4080 Super
- Driver/LLVM version:  nvidia 580.82.09
- Kernel version:   6.16.7
- Link to full system information report: https://gist.github.com/chungyinleo/e56fcedc58678c7e2536355337e64ce3
- Proton version: GE-Proton-10-15

## I confirm:
- [x] that I have verified my problem does NOT happen on proton-experimental and ONLY happens on GE-Proton: The game itself does not seem to work on proton-experimental
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

 

[steam-3489700.log](https://github.com/user-attachments/files/22435992/steam-3489700.log)

## Symptoms 
With UE4SS installed, the game would not load UE4SS mods or crashes at splash screen on GE-Proton-10-13 to GE-Proton-10-15. Whether it crashes or launches but without mods loaded seem to be random. Everything works fine with GE-Proton-10-12 or earlier.

## Reproduction
Install custom build of UE4SS for Stellar Blade from https://github.com/Chrisr0/RE-UE4SS/releases/tag/3.1.0-6
Launch the game with GE-Proton-10-13 or newer

**Comment by GloriousEggroll** [comment]
closing, same problem already resolved here:

https://github.com/GloriousEggroll/proton-ge-custom/issues/236#issuecomment-3224407013

https://github.com/Open-Wine-Components/umu-protonfixes/commit/3f7ab487782bbf96a7705f0e4f81726beebf3a9f

TLDR:

`WINEDLLOVERRIDES="dwmapi=n,b" %command%`

**Comment by chungyinleo** [comment]
Issue persists with said launch option on GE-Proton-10-15. Does it only work after the protonfixes commit arrives with the new version of GE-Proton?

**Comment by GloriousEggroll** [comment]
> Issue persists with said launch option on GE-Proton-10-15. Does it only work after the protonfixes commit arrives with the new version of GE-Proton?

sorry i had to edit the command, it's
`WINEDLLOVERRIDES="dwmapi=n,b" %command%`
